### ISSUE TITLE
Add Crouzeix-Raviart (conforming) element

### ISSUE THREAD

**Issue by bhaveshshrimali** [mscroggs/defelement.com#107]
Hi @mscroggs,

Would it be possible to implement the [conforming CR elements, 4.13 & 4.36](http://archive.numdam.org/article/M2AN_1973__7_3_33_0.pdf) on simplices that can be used downstream in dolfinx? It is useful in mixed-formulations in incompressible elasticity/stokes with discontinuous approximations for the pressure. I could offer some spare hours over the summer in helping implement it if you can point me to the resources. 

The basis functions on reference element (triangle and tetrahedron) are in the paper by Crouzeix and Raviart linked above. The approximation involves a `P2` + `Bubble` + `FacetBubble` in 3D and a `P2` + `Bubble` in 2D if I got it right.

**Reference(s)**
* http://archive.numdam.org/article/M2AN_1973__7_3_33_0.pdf
* 3.2.3 in https://link.springer.com/content/pdf/10.1007%2F978-3-642-87047-7.pdf
* 2.2 in https://link.springer.com/content/pdf/10.1007%2F978-3-642-61623-5.pdf

**Comment by mscroggs** [comment]
In 2D, this looks like it might be the same as the element currently called [bubble enriched Lagrange](https://defelement.com/elements/bubble-enriched-lagrange.html), but I don't yet have the 3D version or the name "conforming Crouzeix-Raviart". I'll get to work adding them.

Thanks for including detailed references, that's very helpful.

**Comment by bhaveshshrimali** [comment]
Thanks ! There is a small typo in the basis function (nodal) in the Crouzeix-Raviart paper (1973). They should be λᵢ⋅(2⋅λᵢ - 1) + 3⋅λ₁⋅λ₂⋅λ₃ in 4.13.

Indeed in 2D this might be similar to the bubble enriched Lagrange, with basically a `P2` Lagrange + a `B3` internal bubble. 

Since these were introduced in the same paper as the P1-nonconforming Crouzeix-Raviart element (often simply called as the Crouzeix-Raviart element), I like to distinguish these two as "conforming" and "non-conforming" respectively. We do have some work using these http://pamies.cee.illinois.edu/Publications_files/JMPS2021c.pdf but I would agree that the terminology isn't super popular in general.
