### ISSUE TITLE
Add Bernardi-Raugel element

### ISSUE THREAD

**Issue by mscroggs** [mscroggs/defelement.com#67]

**Comment by wence-** [comment]
C. Bernardi and G. Raugel, Analysis of Some Finite Elements for the Stokes Problem, Math. Comp., 44(169):71–79, 1985

**Comment by wence-** [comment]
Presumably closable due to #79.

**Comment by mscroggs** [comment]
I've closed this and opened #100, as there were multiple elements in that paper that I want to check if we have
